"""Sample data loaded on application startup (idempotent)."""

SEED_SOURCE = "startup_seed"
DEFAULT_TEST_PASSWORD = "TestPassword123!"

TEST_USERS = [
    {
        "email": "admin@test.local",
        "first_name": "Alex",
        "last_name": "Admin",
        "role": "admin",
    },
    {
        "email": "teacher@test.local",
        "first_name": "Taylor",
        "last_name": "Teacher",
        "role": "teacher",
    },
    {
        "email": "student@test.local",
        "first_name": "Sam",
        "last_name": "Student",
        "role": "student",
    },
    {
        "email": "student2@test.local",
        "first_name": "Jordan",
        "last_name": "Learner",
        "role": "student",
    },
]

SAMPLE_QUESTIONS = [
    {
        "exam_type": "SAT",
        "subject": "Math",
        "topic": "Algebra",
        "difficulty": "Easy",
        "skill_category": "Linear Equations",
        "question_text": "If 2x + 5 = 17, what is x?",
        "options": ["6", "4", "5", "7"],
        "answer": "6",
        "explanation": "Subtract 5 from both sides to get 2x = 12, then divide by 2.",
        "strategy_tip": "Isolate the variable one step at a time.",
        "estimated_time": 45,
    },
    {
        "exam_type": "SAT",
        "subject": "Math",
        "topic": "Algebra",
        "difficulty": "Medium",
        "skill_category": "Systems",
        "question_text": "If 3x + y = 11 and x - y = 1, what is x?",
        "options": ["2", "3", "4", "5"],
        "answer": "3",
        "explanation": "Add the equations: 4x = 12, so x = 3.",
        "strategy_tip": "Look for elimination when coefficients align.",
        "estimated_time": 60,
    },
    {
        "exam_type": "SAT",
        "subject": "Math",
        "topic": "Advanced Math",
        "difficulty": "Hard",
        "skill_category": "Quadratics",
        "question_text": "What is the positive solution to x^2 - 5x + 6 = 0?",
        "options": ["2", "3", "5", "6"],
        "answer": "3",
        "explanation": "Factor: (x - 2)(x - 3) = 0, so x = 2 or 3. The positive solution listed is 3.",
        "strategy_tip": "Try factoring before using the quadratic formula.",
        "estimated_time": 75,
    },
    {
        "exam_type": "SAT",
        "subject": "Math",
        "topic": "Geometry",
        "difficulty": "Medium",
        "skill_category": "Angles",
        "question_text": "A triangle has angles measuring 50° and 60°. What is the third angle?",
        "options": ["70°", "80°", "90°", "100°"],
        "answer": "70°",
        "explanation": "Angles in a triangle sum to 180°, so 180 - 110 = 70°.",
        "strategy_tip": "Memorize the 180° triangle rule.",
        "estimated_time": 50,
    },
    {
        "exam_type": "SAT",
        "subject": "Math",
        "topic": "Problem Solving",
        "difficulty": "Medium",
        "skill_category": "Ratios",
        "question_text": "A recipe uses flour and sugar in a 5:2 ratio. If you use 15 cups of flour, how many cups of sugar?",
        "options": ["4", "5", "6", "7"],
        "answer": "6",
        "explanation": "15 flour is 3 times 5, so sugar is 3 times 2 = 6.",
        "strategy_tip": "Scale both parts of the ratio by the same factor.",
        "estimated_time": 55,
    },
    {
        "exam_type": "SAT",
        "subject": "Math",
        "topic": "Data Analysis",
        "difficulty": "Easy",
        "skill_category": "Mean",
        "question_text": "What is the mean of 4, 8, 10, and 14?",
        "options": ["8", "9", "10", "11"],
        "answer": "9",
        "explanation": "Sum is 36; divide by 4 to get 9.",
        "strategy_tip": "Check whether the mean must be one of the listed values.",
        "estimated_time": 40,
    },
    {
        "exam_type": "PSAT",
        "subject": "Math",
        "topic": "Trigonometry",
        "difficulty": "Hard",
        "skill_category": "Right Triangles",
        "question_text": "In a right triangle, sin(theta) = 3/5. What is cos(theta)?",
        "options": ["3/5", "4/5", "5/4", "5/3"],
        "answer": "4/5",
        "explanation": "Opposite = 3, hypotenuse = 5, adjacent = 4, so cos = 4/5.",
        "strategy_tip": "Draw a 3-4-5 triangle when sine is given.",
        "estimated_time": 70,
    },
    {
        "exam_type": "PSAT",
        "subject": "Reading",
        "topic": "Reading Comprehension",
        "difficulty": "Medium",
        "skill_category": "Main Idea",
        "passage": "City planners argue that adding bike lanes reduces traffic congestion by encouraging short trips without cars.",
        "question_text": "What is the main idea of the passage?",
        "options": [
            "Bike lanes always eliminate traffic.",
            "Bike lanes may reduce congestion for short trips.",
            "Cars are banned in all cities.",
            "Planners dislike public transit.",
        ],
        "answer": "Bike lanes may reduce congestion for short trips.",
        "explanation": "The passage links bike lanes to fewer short car trips, not total elimination of traffic.",
        "strategy_tip": "Avoid extreme words like 'always' unless the text supports them.",
        "estimated_time": 65,
    },
    {
        "exam_type": "SAT",
        "subject": "Reading",
        "topic": "Vocabulary",
        "difficulty": "Easy",
        "skill_category": "Context Clues",
        "question_text": "Because the speaker was candid, the audience trusted her remarks. 'Candid' most nearly means:",
        "options": ["honest", "silent", "angry", "confused"],
        "answer": "honest",
        "explanation": "Candid means frank or truthful, which explains why the audience trusted her.",
        "strategy_tip": "Use surrounding tone and consequences to infer word meaning.",
        "estimated_time": 45,
    },
    {
        "exam_type": "PSAT 8/9",
        "subject": "Writing",
        "topic": "Grammar",
        "difficulty": "Easy",
        "skill_category": "Agreement",
        "question_text": "Choose the correct sentence.",
        "options": [
            "The student are ready.",
            "The students is ready.",
            "The students are ready.",
            "The student ready.",
        ],
        "answer": "The students are ready.",
        "explanation": "Plural subject 'students' requires plural verb 'are'.",
        "strategy_tip": "Identify the subject before choosing the verb form.",
        "estimated_time": 40,
    },
    {
        "exam_type": "SAT",
        "subject": "Writing",
        "topic": "Writing",
        "difficulty": "Medium",
        "skill_category": "Transitions",
        "question_text": "Which transition best completes the sentence? 'The experiment failed; ____, the team revised the hypothesis.'",
        "options": ["therefore", "meanwhile", "for example", "in contrast"],
        "answer": "therefore",
        "explanation": "A failed experiment logically leads to revising the hypothesis (cause and effect).",
        "strategy_tip": "Match transition words to the logical relationship between clauses.",
        "estimated_time": 50,
    },
    {
        "exam_type": "PSAT",
        "subject": "Math",
        "topic": "Algebra",
        "difficulty": "Easy",
        "skill_category": "Inequalities",
        "question_text": "Which value satisfies 2x - 3 < 7?",
        "options": ["2", "4", "6", "8"],
        "answer": "4",
        "explanation": "2x < 10, so x < 5. Only 4 is less than 5 among the choices.",
        "strategy_tip": "Test boundary values near the inequality limit.",
        "estimated_time": 45,
    },
]
